### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by OsloAI** [neptune-ml/open-solution-salt-identification#91]
Could you tell me how to fix blew issues? Thank you very much.

Traceback (most recent call last):
  File "/home/work/tsg/main.py", line 771, in <module>
    train_evaluate_predict_cv()
  File "/home/work/tsg/main.py", line 504, in train_evaluate_predict_cv
    fold_id)
  File "/home/work/tsg/main.py", line 600, in fold_fit_evaluate_predict_loop
    iou, iout, predicted_masks_valid = fold_fit_evaluate_loop(train_data_split, valid_data_split, fold_id)
  File "/home/work/tsg/main.py", line 637, in fold_fit_evaluate_loop
    pipeline_network.fit_transform(train_pipe_input)
  File "/home/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 317, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 323, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/home/work/tsg/common_blocks/utils.py", line 453, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/home/anaconda3/lib/python3.6/site-packages/steppy/base.py", line 605, in fit_transform
    self.fit(*args, **kwargs)
  File "/home/work/tsg/common_blocks/models.py", line 75, in fit
    self.callbacks.on_batch_end(metrics=metrics)
  File "/home/work/tsg/common_blocks/callbacks.py", line 120, in on_batch_end
    callback.on_batch_end(*args, **kwargs)
  File "/home/work/tsg/common_blocks/callbacks.py", line 151, in on_batch_end
    loss = loss.data.cpu().numpy()[0]
IndexError: too many indices for array

**Comment by kamil-kaczmarek** [comment]
Hey @OsloAI, make sure that you installed correct version of PyTorch (0.3.1).
