### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by OsloAI** [neptune-ml/open-solution-salt-identification#93]
COULD YOU TELL ME HOW TO FIX IT, THANKS 

Downloading: "https://download.pytorch.org/models/resnet152-b121ed2d.pth" to /ddn/home/.torch/models/resnet152-b121ed2d.pth
Traceback (most recent call last):
  File "/ddn/data/enteESC[Denter/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/ddn/data/enteESC[Denter/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/ddn/data/enteESC[Denter/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/ddn/data/enteESC[Denter/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/ddn/data/enteESC[Denter/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/ddn/data/enteESC[Denter/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/ddn/data/enteESC[Denter/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/ddn/data/enteESC[Denter/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/ddn/data/enteESC[Denter/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ddn/home/lxdc43/kaggle/salt_identification/main.py", line 771, in <module>
    train_evaluate_predict_cv()
  File "/ddn/home/kaggle/salt_identification/main.py", line 504, in train_evaluate_predict_cv
    fold_id)
  File "/ddn/home/kaggle/salt_identification/main.py", line 600, in fold_fit_evaluate_predict_loop
    iou, iout, predicted_masks_valid = fold_fit_evaluate_loop(train_data_split, valid_data_split, fold_id)
  File "/ddn/home/kaggle/salt_identification/main.py", line 635, in fold_fit_evaluate_loop
    pipeline_network = unet(config=config, suffix='_fold_{}'.format(fold_id), train_mode=True)
  File "/ddn/home/kaggle/salt_identification/main.py", line 268, in unet
    transformer=models.PyTorchUNet(**config.model['unet']),
  File "/ddn/home/kaggle/salt_identification/common_blocks/models.py", line 50, in __init__
    self.set_model()
  File "/ddn/home/kaggle/salt_identification/common_blocks/models.py", line 160, in set_model
    **config['model_config'])
  File "/ddn/home/lxdc43/kaggle/salt_identification/common_blocks/unet_models.py", line 114, in __init__
    self.encoder = torchvision.models.resnet152(pretrained=pretrained)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/site-packages/torchvision/models/resnet.py", line 212, in resnet152
    model.load_state_dict(model_zoo.load_url(model_urls['resnet152']))
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 64, in load_url
    _download_url_to_file(url, cached_file, hash_prefix)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 69, in _download_url_to_file
    u = urlopen(url)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/ddn/data/lxdc43/enteESC[Denter/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

**Comment by kamil-kaczmarek** [comment]
Hi @OsloAI, it seems that your Internet connection got interrupted. Another idea is that pytorch host is down.
